version: "3"
services:
  movie-catch-api:
    image: fredsonchaves07/movie-catch-api
    container_name: movie-catch-api
    restart: always
    ports:
      - "8081:8080"
    environment:
      - PROFILE_ACTIVE=docker
      - JWT_TOKEN_EXPIRATION=7200000
      - JWT_TOKEN_SECRET=753778214125442A472D4B6150645367566B59703373367638792F423F452848
    links:
      - movie-catch-database
    depends_on:
      - movie-catch-database

  movie-catch-database:
    image: postgres
    container_name: movie-catch-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=movie-catch
      - POSTGRES_DB=moviecatchdb
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local