name: CI/CD for Prod Heroku

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  java:
    name: build java

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: Run tests and build project
        env:
          PROFILE_ACTIVE: 'test'
        run: mvn clean install

  #      - name: Build & push Docker image
  #        uses: mr-smithers-excellent/docker-build-push@v5
  #        with:
  #          image: fredsonchaves07/movie-catch-api
  #          tags: latest
  #          registry: docker.io
  #          dockerfile: Dockerfile
  #          username: ${{ secrets.DOCKER_USERNAME }}
  #          password: ${{ secrets.DOCKER_PASSWORD }}

  docker:
    name: build docker image
    needs: java
    depends: java

    steps:
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: fredsonchaves07/movie-catch-api
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}